import type { Metadata } from "next";
import "./globals.css";
import {MoovingProvider} from "@/Utils/Provider";
import React from "react";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MoovingProvider>
            {children}
        </MoovingProvider>

      </body>
    </html>
  );
}
